[Variables]
DynamicVariables=1
@include="#SKINSPATH#\RainyBitcoin\Variables.inc"

;-- Color of Bitcoin Icon
;   Options: Orange, Black, White
Bitcoin=#Orange#

;-- Currency (This only affects MtGox)
;   Options: USD, AUD, CAD, CHF, CNY, DKK, EUR, GBP, HKD, JPY, NZD, PLN, RUB, SEK, SGD, THB
Currency=#USD#

;-- Exchange (Minimal Ticker Only)
;   Options: MtGox, Bitstamp
Exchange=#MtGox#

;-- Line Color (Graph)
;   Options: Any rgba or hex value
;   e.g. 255,255,255,255 / ffffff
MtGoxColor=FFCC33
BitstampColor=3366FF